### ISSUE TITLE
일관된 에러 처리

### ISSUE THREAD

**Issue by sktkddn777** [ZeroWastePlatform/BackEnd#24]
[관련자료](https://jeong-pro.tistory.com/195) 를 참고하여 일관된 에러 처리를 진행할 예정

@RestController에서 예외가 발생하든 @Controller에서 예외가 발생하든 @ControllerAdvice + @ExceptionHandler 조합으로 처리가 가능한 점을 사용할 예정입니다.

이슈 #21 작업이 끝나면 이어서 작업할 예정

**Comment by Jindoryy** [comment]
제가 아직 구현한 기능에 대해 에러처리를 하지 않았는데 담당한 기능을 모두 구현하고 나서 
올려주신 관련자료 참고해서 에러처리 동일하게 진행하도록 하겠습니다!

**Comment by sktkddn777** [comment]
네!! 에러 처리 방식은 통일하는게 좋을 듯하여 지금 진행하는 인증 부분만 마무리 하고 예외 처리 작업 진행하도록 하겠습니다!!
