### ISSUE TITLE
도메인 구조 문제

### ISSUE THREAD

**Issue by sktkddn777** [ZeroWastePlatform/BackEnd#4]
## 구현해야 할 부분
- 도메인별로 패키지 구조 설계를 진행한다.

## 문제
- 다대다 관계에서 중간에 다대일 일대다로 풀어주는 테이블을 어떤식으로 패키지 구조를 나눌지 고민

## 방안
`post`와 `hashtag` 사이의 관계에 `post_hashtag` 가 있다 가정
1. 따로 패키지를 만든다
	1-1. post_hashtag 패키지를 만든다
	1-2. 아예 따른 이름을 생각해서 적용하기

2. `post_hashtag` 도메인을 hashtag 도메인에 추가 시키기 -> hashtag 도메인 안에 PostHashtag 엔티티 클래스 생성하는 방식으로

개인적으로는 2번 방안이 괜찮아보임. 관련 깃허브 [레포](https://github.com/woowacourse-teams/2022-sokdak)도 있습니다.

**Comment by Jindoryy** [comment]
관련 깃허브 레포 확인해보니 저도 따로 post_hashtag를 만드는 것보단 hashtag도메인 안에 넣는 것이 좋아 보입니다.
POST - HASH_TAG 관계는 다대일 일대다 관계로 ERD cloud에 수정사항 반영 해놓겠습니다.

**Comment by starwook** [comment]
저도 2번이요~!
