### ISSUE TITLE
Pull request 탬플릿 설정

### ISSUE THREAD

**Issue by sktkddn777** [ZeroWastePlatform/BackEnd#5]
PR 탬플릿을 설정하려고 합니다. 탬플릿 안에 필요한 내용 추가적으로 있다면 알려주세요

1. 구현 기능
2. 세부 구현 기능
3. 관련 이슈

**Comment by Jindoryy** [comment]
구성해주신 템플릿 좋은것 같습니다.
추가적으로 PR 범위를 작게 가져갔으면 좋을 것 같습니다. 불가피 하게 범위를 크게 PR을 한다면 [중요한 부분]과 같은 항목을 추가해서 중점적으로 어디를 리뷰를 봐야할지 강조해주는게 좋을 것 같습니다.

템플릿 확정되면 PR 템플릿 등록해서 공통으로 사용할 수 있게 하면 좋겠습니다!
