### ISSUE TITLE
클래스 및 메소드 이름 통일

### ISSUE THREAD

**Issue by sktkddn777** [ZeroWastePlatform/BackEnd#56]
클래스 이름과 메소드 이름이 현재 통일성이 없다고 생각되어 이를 통일 시키는게 좋을 거 같아요

https://naver.github.io/hackday-conventions-java/#method-verb-preposition

**Comment by Jindoryy** [comment]
조회 -> get
작성 -> create
수정 -> update
검색 -> search
인기 -> popular
추천 -> recommend
