### ISSUE TITLE
AWS S3 첨부파일 캐싱을 위한 CDN 적용

### ISSUE THREAD

**Issue by Jindoryy** [ZeroWastePlatform/BackEnd#89]
웹 사이트 전체적인 이미지들에 대한 로딩 속도 개선을 위해 AWS S3 부분에 CDN을 적용할려고 합니다.

[CDN을 이해하고 적용하기 위해 참고한 블로그](https://velog.io/@doohyunlm/AWS-CloudFront-%EA%B0%9C%EB%85%90)
[CDN을 이해하고 적용하기 위해 참고한 블로그 (2)](https://jjuunn.tistory.com/31)

**Comment by sktkddn777** [comment]
CDN 을 사용하기 위해선 결국 AWS에서 CloudFront 를 적용하면 된다라고 이해했는데 맞을까요?

**Comment by Jindoryy** [comment]
> CDN 을 사용하기 위해선 결국 AWS에서 CloudFront 를 적용하면 된다라고 이해했는데 맞을까요?

네 맞습니다.
CloudFront 도메인을 이용해서 S3(이미지 파일 스토리지)에 접근할 수 있도록 했습니다
